### ISSUE TITLE
Github Actions to verify bit-perfectness?

### ISSUE THREAD

**Issue by Awuwunya** [cvghivebrain/s1disasm#14]
as I assume the goal is still to keep bit-perfectness intact, why not introduce Github actions to check for that automatically? I can give it a shot to create a script for this (although I can't create the workflow myself), that would basically just give a little checkmark or x icon next to each commit to make sure bit-perfectness works. This should be fairly easy to setup with minimal changes to the actual disassembly itself as well, given it can just run the assembler natively, and compare outputs to the rev00 and rev01 ROMs. This should help make sure that all commits are still bit-perfect. This would probably also be only a check, rather than directly rejecting commits based on the result.

The only caveat I can see, that sometimes gha is a little flakey, so there may be false negatives from time to time. It's easy to check if it failed, and I don't expect it to do so very often.

**Comment by cvghivebrain** [comment]
Sounds good. Does Github actually run the exe in s1disasm, or does it run its own assembler?
