### ISSUE TITLE
Use rs lists over equates whenever possible

### ISSUE THREAD

**Issue by NatsumiFox** [cvghivebrain/s1disasm#2]
A major issue with equates when it comes to things like RAM mappings, ost definitions or sound driver RAM offsets is that you lose the ability to rearrange them dynamically depending on use. You could for example need to add a new array into RAM, but the difficulty is finding the appropriate amount of space. If you use an equate list, you will have to rearrange a lot of them, and you are likely to slot RAM addresses you want to move just anywhere they fit, rather than to keep the structure intact. Similar problems occur when you are trying to remove RAM addresses that are no longer necessary.

This is where rs tables come in handy. They provide the ability to rather than define a strict address, they rather allow you to use a size, and have the assembler resolve addresses automatically. They still do the same thing, but allow for insertion or deletion of items, and also are by definition showing the size of the array, so there is no confusion on that front either. It also provides automatic alignment with the instruction size parameter as well.

[Here is an example of how I have used them in AMPS.](https://github.com/NatsumiFox/AMPS-Sonic-1-Git/blob/master/AMPS/code/macro.asm#L206)

**Comment by Brainulator9** [comment]
At the same time, I find it easier to work with things when I can easily tell what address a given RAM equate goes to, especially when it seems that certain addresses are aligned to certain boundaries (e.g. the sound driver is allotted $600 bytes starting at $FFF000, background positioning is at $FFF700, $FFFE00 is the initial stack pointer).

I also wonder: when it comes to addresses that currently do not have names, would a construction like "unk_FFFF" be recommendable under these circumstances? It seems like there's an effort to name all RAM addresses at some point, but RS-ing everything forces all RAM variables, used or not, to have names, and I worry this might be putting the cart before the horse.

**Comment by Brainulator9** [comment]
Eh, I'll live. I do wonder if it would be worth it to put in the comments what the RAM address equates to in an unmodified ROM.

**Comment by NatsumiFox** [comment]
btw need help with this (or anything else for that matter)? been working on this a while ago (including updating the wiki) and certainly know Sonic 1 as a whole, so I think I can chip in some help, just if I knew what to do :P
