### ISSUE TITLE
Z80 "AND" and "SUB" instructions use wrong macro parameter for "getzreg"

### ISSUE THREAD

**Issue by Ralakimus** [cvghivebrain/s1disasm#28]

**Comment by Ralakimus** [comment]
Also, ASM68K does not play nicely with spaces in if statements. Was using this to program some Z80 stuff and I've had
`ld	de,(284h-508h)*2` assemble as `ld	de,((284h-508h)*2)`

**Comment by Brainulator9** [comment]
> Also, ASM68K does not play nicely with spaces in if statements. Was using this to program some Z80 stuff and I've had `ld de,(284h-508h)*2` assemble as `ld de,((284h-508h)*2)` because it wasn't even applying the 2nd strcmp. It might be worth looking into a better way to detect parenthesis, because I can see stuff like `ld a,(num1)*(num2)` becoming an issue.

Does this include with the WS assembler option on?

**Comment by Ralakimus** [comment]
...it DOES help to have that on lol.
