### ISSUE TITLE
Incorrect constant name in spike bug fix

### ISSUE THREAD

**Issue by OrionNavattan** [cvghivebrain/s1disasm#31]
The disassembly fails to build if the revision is set to 2 due to an incorrectly-named constant. ost_sonic_flash_rate is used instead of the correct ost_sonic_flash_time.

https://github.com/cvghivebrain/s1disasm/blob/c67d7b4d7dcb24528221b041a2bd78b03e6e114a/Objects/Spikes.asm#L107

**Comment by cvghivebrain** [comment]
Fixed it, thanks.
