### ISSUE TITLE
Zonewarning macro number format

### ISSUE THREAD

**Issue by OrionNavattan** [cvghivebrain/s1disasm#36]
This caused quite a headache while trying to get this working in my Sonic 2 disasm. The zonewarning macro has a bit of an issue with the number formats in its warning message: ($\#ZoneCount) actually prints a decimal number rather than a hexadecimal one.

https://github.com/cvghivebrain/s1disasm/blob/6b8b30db1450941da51abf8c02a29a39f00f1206/Macros.asm#L296

**Comment by cvghivebrain** [comment]
I think I fixed it by making ZoneCount a parameter for inform.

By the way, there was also a mislabeled VDP register. $8140 enables display rather than disabling it.

**Comment by OrionNavattan** [comment]
That does appear to have fixed the issue. :>

And I actually came to the same conclusion with that register name. It didn't make much sense when it was used as a constant in the enable and disable display macros. xD
