### ISSUE TITLE
Duplicate layer deformation code

### ISSUE THREAD

**Issue by Brainulator9** [cvghivebrain/s1disasm#6]
For some reason, two copies of the layer deformation code can be found, one in the sonic.asm file and another in their own file. No, I don't mean between REV00 and REV01. The split files, however, seem to only be included if the Revision variable is set to 0... during code that only assembles if Revision is set to 1.

**Comment by cvghivebrain** [comment]
Fixed. It was the result of me merging all the asm files and then not re-splitting them properly.
